"use strict";

/**
 * TOR-444: After princes_court_trait_placeholders expands the referenceLayer .build file,
 * extract the Prince's Court subtree into ui/shared/panel_ref_princes_court.xml (no viewer
 * @@color@@) and remove Court from the color template source + .build so ×5 generation
 * only keeps coteries in the per-seat referenceLayer.
 *
 * Usage (from repo root):
 *   node .dev/scripts/princes_court_trait_placeholders.js
 *   node .dev/scripts/extract_shared_princes_court.js
 *   node .dev/scripts/xml_color_template_generator.js --templateDir ui/.templates
 *   npm run ui-global-xml:embed
 */

const fs = require("fs");
const path = require("path");

const projectRoot = path.resolve(__dirname, "../..");
const SOURCE = path.join(projectRoot, "ui/.templates/panel_right_sidebar_referenceLayer.xml");
const BUILD = path.join(projectRoot, "ui/.templates/.build/panel_right_sidebar_referenceLayer.xml");
const SHARED_OUT = path.join(projectRoot, "ui/shared/panel_ref_princes_court.xml");

const startMark = '  <Panel id="playerHud_refPanel_princesCourt_@@color@@"';
const endMark = '  <Panel id="playerHud_refPanel_coteries_@@color@@"';

function stripCourt(xml, label) {
  const start = xml.indexOf(startMark);
  const end = xml.indexOf(endMark);
  if (start < 0 || end < 0) {
    throw new Error(`[extract_shared_princes_court] Court markers missing in ${label} start=${start} end=${end}`);
  }
  const court = xml.slice(start, end);
  const rest =
    xml.slice(0, start) +
    "  <!-- Prince's Court: ui/shared/panel_ref_princes_court.xml (TOR-444). -->\n\n" +
    xml.slice(end);
  return { court, rest };
}

function toSharedCourt(courtXml, defaultsXml) {
  let court = courtXml.replace(/_@@color@@/g, "");
  if (court.includes("@@color@@")) {
    throw new Error("[extract_shared_princes_court] @@color@@ remains after strip");
  }
  court = court.replace(
    /id="playerHud_refPanel_princesCourt"/,
    'id="playerHud_refPanel_princesCourt" visibility="None"'
  );
  court = court.replace(
    /id="playerHud_refPanel_PrincesCourt_page(\d)" class="princesCourt-page"/g,
    'id="playerHud_refPanel_PrincesCourt_page$1" class="princesCourt-page" visibility="None"'
  );
  court = court.replace(
    /id="playerHud_refPanel_PrincesCourt_page1" class="princesCourt-page" visibility="None">/,
    'id="playerHud_refPanel_PrincesCourt_page1" class="princesCourt-page" visibility="None" active="false">'
  );
  const header = `<!-- Shared Prince's Court reference (TOR-444). Generated by extract_shared_princes_court.js.
     Audience: root + page panels via U.showTo/hideFrom. Tracker ids: box_*_<PanelSeat> (no HUD viewer suffix).
-->
`;
  // Wrap with a container so Court Defaults apply (they previously lived on the per-seat referenceLayer).
  const body =
    '<Panel id="playerHud_princesCourt_sharedRoot" class="popupImageContainer">\n' +
    defaultsXml.trim() +
    "\n" +
    court.trim() +
    "\n</Panel>\n";
  return header + body;
}

if (!fs.existsSync(BUILD)) {
  throw new Error("[extract_shared_princes_court] Missing .build referenceLayer — run princes_court_trait_placeholders.js first");
}

const buildXml = fs.readFileSync(BUILD, "utf8");
if (!buildXml.includes(startMark)) {
  if (fs.existsSync(SHARED_OUT)) {
    console.log("[extract_shared_princes_court] Court already extracted; shared file present — no-op");
    process.exit(0);
  }
  throw new Error("[extract_shared_princes_court] Court missing from .build and no shared file");
}

const { court: courtFromBuild, rest: buildRest } = stripCourt(buildXml, "build");

const defaultsMatch = buildXml.match(/<Defaults>[\s\S]*?<\/Defaults>/);
if (!defaultsMatch) {
  throw new Error("[extract_shared_princes_court] Defaults block not found in build referenceLayer");
}

fs.writeFileSync(SHARED_OUT, toSharedCourt(courtFromBuild, defaultsMatch[0]), "utf8");
fs.writeFileSync(BUILD, buildRest, "utf8");

const sourceXml = fs.readFileSync(SOURCE, "utf8");
if (sourceXml.includes(startMark)) {
  const { rest: sourceRest } = stripCourt(sourceXml, "source");
  fs.writeFileSync(SOURCE, sourceRest, "utf8");
}

console.log("[extract_shared_princes_court] Wrote", path.relative(projectRoot, SHARED_OUT));
console.log("[extract_shared_princes_court] Stripped Court from .build (+ source if present)");
