"use strict";

/**
 * Extracts Storyteller Dashboard Scenes-tab catalogs from Lua sources of truth.
 *
 * Writes:
 *   .dev/storyteller-dashboard/data/scene-catalogs.json
 *   .dev/storyteller-dashboard/data/control-board-snaps.json
 *
 * Run from repo root: node .dev/scripts/generate_dashboard_scene_catalogs.js
 * Polar snap stagger uses STAGE_BOARD Transform from the live TTS save
 * (`tts-assets.config.json` savesDir + defaultSaveName), not D.DEFAULT_STAGE_WORLD.
 * Chained from `npm run dashboard:scene-catalogs` (`build:all-tooling`) and from
 * Storyteller Dashboard `npm run dev` / `npm run build`.
 */

const fs = require("fs");
const path = require("path");
const { resolveSavePath } = require("../../.tools/tts-save/resolve-save-path");

const root = path.resolve(__dirname, "..", "..");
const constantsPath = path.join(root, "lib", "constants.ttslua");
const skyboxesPath = path.join(root, "lib", "skyboxes_catalog.ttslua");
const soundscapePath = path.join(root, "lib", "soundscape_catalog.ttslua");
const conditionDefsPath = path.join(root, "lib", "condition_defs.ttslua");
const npcsDataPath = path.join(root, "lib", "npcs_data.ttslua");
const gameboardDataPath = path.join(root, "lib", "npc_gameboard_data.ttslua");
const guidsPath = path.join(root, "lib", "guids.ttslua");
const catalogsOutPath = path.join(root, ".dev", "storyteller-dashboard", "data", "scene-catalogs.json");
const snapsOutPath = path.join(root, ".dev", "storyteller-dashboard", "data", "control-board-snaps.json");

const DO_NOT_EDIT =
  "AUTO-GENERATED by .dev/scripts/generate_dashboard_scene_catalogs.js — DO NOT EDIT BY HAND. Regenerate: npm run dashboard:scene-catalogs";

const REQUIRED_PC_KEYS = ["aishe", "rashid", "lordLucien", "fomorach", "blackCaesar"];
const REQUIRED_PLAYER_COLORS = ["Brown", "Orange", "Red", "Pink", "Purple"];
const REQUIRED_NPC_SEATS = ["NPC1", "NPC2", "NPC3", "NPC4"];
const REQUIRED_SCATTER_AREAS = ["scatter1", "scatter2", "scatter3", "scatter4", "scatter5", "scatter6"];
const PALETTE_GROUP_BLACKLIST = { princesCourt: true };

/** Dashboard `controlBoard_standard.webp` seats: slot 1 is at image center (u = 0.50). */
const DASHBOARD_SEAT_ROW_UV = { uMin: 0.35, uMax: 0.65 };

/**
 * @param {string} guidsSrc
 * @returns {string}
 */
function readStageBoardGuid(guidsSrc) {
  const match = guidsSrc.match(/STAGE_BOARD\s*=\s*"([0-9a-fA-F]+)"/);
  if (!match) {
    throw new Error('lib/guids.ttslua is missing STAGE_BOARD = "...".');
  }
  return match[1];
}

/**
 * @returns {{ defaultSaveName: string, savesDir: string | undefined }}
 */
function readRepoAssetsConfig() {
  const envPath =
    process.env.TTS_ASSETS_CONFIG && String(process.env.TTS_ASSETS_CONFIG).trim() !== ""
      ? path.resolve(String(process.env.TTS_ASSETS_CONFIG).trim())
      : null;
  const localPath = path.join(root, "tts-assets.config.json");
  const chosen = envPath && fs.existsSync(envPath) ? envPath : fs.existsSync(localPath) ? localPath : null;
  let defaultSaveName = "230";
  /** @type {string | undefined} */
  let savesDir;
  if (chosen) {
    const raw = JSON.parse(fs.readFileSync(chosen, "utf8"));
    if (typeof raw.defaultSaveName === "string" && raw.defaultSaveName.trim() !== "") {
      defaultSaveName = raw.defaultSaveName.trim().replace(/^TS_Save_/i, "").replace(/\.json$/i, "");
    }
    if (typeof raw.savesDir === "string" && raw.savesDir.trim() !== "") {
      const resolved = path.resolve(raw.savesDir.trim());
      if (fs.existsSync(resolved)) {
        savesDir = resolved;
      }
    }
  }
  return { defaultSaveName, savesDir };
}

/**
 * @param {string} defaultSaveName
 * @param {string | undefined} savesDir
 * @returns {{ savePath: string, saveFileName: string, source: "savesDir" | "dev-snapshot" }}
 */
function resolveChronicleSaveFile(defaultSaveName, savesDir) {
  const live = resolveSavePath(defaultSaveName, savesDir);
  if (fs.existsSync(live.savePath)) {
    return { savePath: live.savePath, saveFileName: live.saveFileName, source: "savesDir" };
  }
  const snapshotName = `TS_Save_${defaultSaveName}.json`;
  const snapshot = path.join(root, ".dev", snapshotName);
  if (fs.existsSync(snapshot)) {
    return { savePath: snapshot, saveFileName: snapshotName, source: "dev-snapshot" };
  }
  throw new Error(
    `STAGE_BOARD save not found. Expected the live TTS save at ${live.savePath} (tts-assets.config.json savesDir + defaultSaveName). After you resize STAGE_BOARD in Tabletop Simulator, save the game, then re-run npm run dashboard:scene-catalogs or start the dashboard with npm run dev. Optional fallback: copy that save to .dev/${snapshotName}.`,
  );
}

/**
 * @param {string} block
 * @param {string} key
 * @returns {number}
 */
function readTransformNumber(block, key) {
  const match = block.match(new RegExp(`"${key}":\\s*(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?)`));
  if (!match) {
    throw new Error(`STAGE_BOARD Transform is missing ${key}.`);
  }
  return Number(match[1]);
}

/**
 * @param {string} saveText
 * @param {string} guid
 * @returns {{ posX: number, posZ: number, scaleX: number, scaleZ: number, rotY: number }}
 */
function extractStageBoardTransform(saveText, guid) {
  const marker = `"GUID": "${guid}"`;
  let from = 0;
  while (from < saveText.length) {
    const at = saveText.indexOf(marker, from);
    if (at < 0) {
      throw new Error(`Save has no object GUID ${guid} (G.GUIDS.STAGE_BOARD).`);
    }
    const window = saveText.slice(at, at + 16000);
    if (/"Nickname":\s*"STAGE_BOARD"/.test(window)) {
      const transformMatch = window.match(/"Transform":\s*\{([\s\S]*?)\}/);
      if (!transformMatch) {
        throw new Error(`STAGE_BOARD ${guid} has no Transform block.`);
      }
      const block = transformMatch[1];
      return {
        posX: readTransformNumber(block, "posX"),
        posZ: readTransformNumber(block, "posZ"),
        scaleX: readTransformNumber(block, "scaleX"),
        scaleZ: readTransformNumber(block, "scaleZ"),
        rotY: readTransformNumber(block, "rotY"),
      };
    }
    from = at + marker.length;
  }
  throw new Error(`Found GUID ${guid} but no object nicknamed STAGE_BOARD.`);
}

/**
 * Custom_Tile local ±0.5 × transform scale. Center/half only matter as deltas;
 * polar UVs stay in shared 0–1 board space. Not D.DEFAULT_STAGE_WORLD (440×400).
 *
 * @param {{ posX: number, posZ: number, scaleX: number, scaleZ: number, rotY: number }} transform
 */
function stageWorldFromTransform(transform) {
  const normalizedRotY = ((transform.rotY % 360) + 360) % 360;
  const scaleX = Math.abs(transform.scaleX);
  const scaleZ = Math.abs(transform.scaleZ);
  let halfWidthX = scaleX / 2;
  let halfDepthZ = scaleZ / 2;
  if (Math.abs(normalizedRotY - 90) < 1 || Math.abs(normalizedRotY - 270) < 1) {
    halfWidthX = scaleZ / 2;
    halfDepthZ = scaleX / 2;
  }
  return {
    centerX: transform.posX,
    centerZ: transform.posZ,
    halfWidthX,
    halfDepthZ,
  };
}

/**
 * Live Lua `applyRadialStaggerUv` converts UV through STAGE_BOARD `positionToWorld`.
 *
 * @returns {{
 *   centerX: number,
 *   centerZ: number,
 *   halfWidthX: number,
 *   halfDepthZ: number,
 *   stageBoard: {
 *     guid: string,
 *     saveFileName: string,
 *     source: string,
 *     posX: number,
 *     posZ: number,
 *     scaleX: number,
 *     scaleZ: number,
 *     rotY: number,
 *     halfWidthX: number,
 *     halfDepthZ: number,
 *   },
 * }}
 */
function loadDashboardStageWorld() {
  const guid = readStageBoardGuid(fs.readFileSync(guidsPath, "utf8"));
  const cfg = readRepoAssetsConfig();
  const save = resolveChronicleSaveFile(cfg.defaultSaveName, cfg.savesDir);
  const transform = extractStageBoardTransform(fs.readFileSync(save.savePath, "utf8"), guid);
  const world = stageWorldFromTransform(transform);
  const where = save.source === "savesDir" ? "live TTS save" : "repo .dev snapshot";
  console.log(
    `STAGE_BOARD ${guid} from ${save.saveFileName} (${where}): scale ${transform.scaleX} × ${transform.scaleZ} at (${transform.posX}, ${transform.posZ}), rotY ${transform.rotY}.`,
  );
  return {
    ...world,
    stageBoard: {
      guid,
      saveFileName: save.saveFileName,
      source: save.source,
      posX: transform.posX,
      posZ: transform.posZ,
      scaleX: transform.scaleX,
      scaleZ: transform.scaleZ,
      rotY: transform.rotY,
      halfWidthX: world.halfWidthX,
      halfDepthZ: world.halfDepthZ,
    },
  };
}

/** Palette groups that are not keys in C.CHRONICLE_DATA.coteries. */
const EXTRA_PICKER_GROUP_LABELS = {
  aapilu: "Aapilu",
  civilian: "Civilian",
  criseDeLwa: "Crise de Lwa",
  ducheskiRevenant: "Ducheski Revenant",
  friendlyNeighborhoodSpiders: "Friendly Neighborhood Spiders",
  friendlyNeighborhoodSpidersGarou: "Friendly Neighborhood Spiders (Garou)",
  memoriam: "Memoriam",
  touchstone: "Touchstone",
  Ungrouped: "Ungrouped",
};

/**
 * @param {string} source
 * @param {string} marker
 */
function extractBlock(source, marker) {
  const markerIndex = source.lastIndexOf(marker);
  if (markerIndex < 0) {
    throw new Error(`Missing marker: ${marker}`);
  }
  const startBrace = source.indexOf("{", markerIndex);
  if (startBrace < 0) {
    throw new Error(`Missing opening brace after marker: ${marker}`);
  }
  let depth = 0;
  for (let i = startBrace; i < source.length; i += 1) {
    const ch = source[i];
    if (ch === "{") {
      depth += 1;
    } else if (ch === "}") {
      depth -= 1;
      if (depth === 0) {
        return source.slice(startBrace, i + 1);
      }
    }
  }
  throw new Error(`Unterminated table block for marker: ${marker}`);
}

/**
 * @param {string} tableBlock
 * @returns {{ key: string, body: string }[]}
 */
function parseTopLevelEntries(tableBlock) {
  const entries = [];
  const body = tableBlock.slice(1, -1);
  let i = 0;
  while (i < body.length) {
    while (i < body.length && /[\s,]/.test(body[i])) {
      i += 1;
    }
    if (i >= body.length) {
      break;
    }
    const rest = body.slice(i);
    const quotedMatch = rest.match(/^\["([^"]+)"\]\s*=\s*\{/);
    const identMatch = rest.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\{/);
    const match = quotedMatch || identMatch;
    if (!match) {
      i += 1;
      continue;
    }
    const key = quotedMatch ? quotedMatch[1] : identMatch[1];
    const openIndex = i + match[0].lastIndexOf("{");
    let depth = 0;
    let end = openIndex;
    for (let j = openIndex; j < body.length; j += 1) {
      if (body[j] === "{") {
        depth += 1;
      } else if (body[j] === "}") {
        depth -= 1;
        if (depth === 0) {
          end = j;
          break;
        }
      }
    }
    entries.push({ key, body: body.slice(openIndex, end + 1) });
    i = end + 1;
  }
  return entries;
}

/**
 * @param {string} tableBlock
 * @returns {string[]}
 */
function parseAnonymousTableBodies(tableBlock) {
  const bodies = [];
  const inner = tableBlock.slice(1, -1);
  let i = 0;
  while (i < inner.length) {
    while (i < inner.length && /[\s,]/.test(inner[i])) {
      i += 1;
    }
    if (i >= inner.length) {
      break;
    }
    if (inner[i] !== "{") {
      i += 1;
      continue;
    }
    let depth = 0;
    let end = i;
    for (let j = i; j < inner.length; j += 1) {
      if (inner[j] === "{") {
        depth += 1;
      } else if (inner[j] === "}") {
        depth -= 1;
        if (depth === 0) {
          end = j;
          break;
        }
      }
    }
    bodies.push(inner.slice(i, end + 1));
    i = end + 1;
  }
  return bodies;
}

/**
 * @param {string} expr
 */
function parseLuaNumberExpr(expr) {
  const trimmed = String(expr).trim();
  if (trimmed === "") {
    throw new Error("Empty Lua number expression.");
  }
  if (!/^[\d.\s+\-*/()]+$/.test(trimmed)) {
    throw new Error(`Cannot parse Lua number expression: ${trimmed}`);
  }
  const value = Function(`"use strict"; return (${trimmed});`)();
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new Error(`Lua number expression did not yield a finite number: ${trimmed}`);
  }
  return value;
}

/**
 * @param {string} body
 * @param {string} field
 * @returns {number|null}
 */
function readNumberField(body, field) {
  const match = body.match(new RegExp(`${field}\\s*=\\s*([^,}\\n]+)`));
  if (!match) {
    return null;
  }
  const raw = match[1].replace(/--.*$/, "").trim();
  if (raw === "nil") {
    return null;
  }
  return parseLuaNumberExpr(raw);
}

/**
 * @param {string} body
 * @param {string} field
 * @returns {string|null}
 */
function readStringField(body, field) {
  const match = body.match(new RegExp(`${field}\\s*=\\s*"([^"]*)"`));
  if (match) {
    return match[1];
  }
  const ident = body.match(new RegExp(`${field}\\s*=\\s*([A-Za-z_][A-Za-z0-9_.]*)`));
  if (ident && ident[1] !== "true" && ident[1] !== "false" && ident[1] !== "nil") {
    return ident[1];
  }
  return null;
}

/**
 * @param {string} body
 * @param {string} field
 * @returns {boolean|null}
 */
function readBooleanField(body, field) {
  const match = body.match(new RegExp(`${field}\\s*=\\s*(true|false)\\b`));
  if (!match) {
    return null;
  }
  return match[1] === "true";
}

/**
 * @param {string} body
 */
function readUvOrigin(body) {
  const match = body.match(/origin\s*=\s*\{\s*u\s*=\s*([^,}]+)\s*,\s*v\s*=\s*([^}]+)\s*\}/);
  if (!match) {
    return null;
  }
  return { u: parseLuaNumberExpr(match[1]), v: parseLuaNumberExpr(match[2]) };
}

/**
 * @param {string} body
 */
function readValidSnaps(body) {
  const match = body.match(/validSnaps\s*=\s*\{([^}]*)\}/);
  if (!match) {
    return null;
  }
  const inner = match[1];
  const minU = readNumberField(`{${inner}}`, "minU");
  const maxU = readNumberField(`{${inner}}`, "maxU");
  const minV = readNumberField(`{${inner}}`, "minV");
  const maxV = readNumberField(`{${inner}}`, "maxV");
  if (minU === null || maxU === null || minV === null || maxV === null) {
    throw new Error("CONTROL_BOARD_SNAP validSnaps is missing minU/maxU/minV/maxV.");
  }
  return { minU, maxU, minV, maxV };
}

function familyKBoundsForSnapCount(num) {
  const n = Math.floor(num);
  if (n < 1) {
    return [0, -1];
  }
  const half = Math.floor(n / 2);
  if (n % 2 === 0) {
    return [-half, half - 1];
  }
  return [-half, half];
}

function ringOriginUvForIndex(cfg, ringIndex) {
  const group = cfg.snapGroups[ringIndex - 1];
  if (group && group.origin) {
    return [group.origin.u, group.origin.v];
  }
  return [cfg.origin.u, cfg.origin.v];
}

function ringOriginDiffersFromMaster(cfg, ringIndex) {
  const [ringU, ringV] = ringOriginUvForIndex(cfg, ringIndex);
  return Math.abs(ringU - cfg.origin.u) > 1e-4 || Math.abs(ringV - cfg.origin.v) > 1e-4;
}

function bearingUvDeg(fromU, fromV, toU, toV) {
  return (Math.atan2(toV - fromV, toU - fromU) * 180) / Math.PI;
}

function familyAngleDegForSnap(cfg, ringIndex, rayIndex, familyK, angleDelta, rays) {
  const anchorDeg = (rayIndex / rays) * 360;
  if (!ringOriginDiffersFromMaster(cfg, ringIndex)) {
    return anchorDeg + familyK * angleDelta;
  }
  const [ringOriginU, ringOriginV] = ringOriginUvForIndex(cfg, ringIndex);
  const towardMasterDeg = bearingUvDeg(ringOriginU, ringOriginV, cfg.origin.u, cfg.origin.v);
  return towardMasterDeg + anchorDeg + familyK * angleDelta;
}

function uvOnEllipse(originU, originV, angleDeg, maxU, maxV) {
  const theta = (angleDeg * Math.PI) / 180;
  return [originU + Math.cos(theta) * (maxU - originU), originV + Math.sin(theta) * (maxV - originV)];
}

function snapUvOnBoard(u, v) {
  return typeof u === "number" && typeof v === "number" && u >= 0 && u <= 1 && v >= 0 && v <= 1;
}

function snapUvPassesValidSnaps(group, u, v) {
  if (!group.validSnaps) {
    return true;
  }
  const box = group.validSnaps;
  return u >= box.minU && u <= box.maxU && v >= box.minV && v <= box.maxV;
}

function applyRadialStaggerUv(originU, originV, familyK, radialStagger, u, v, stage) {
  // Same formula as Lua applyRadialStaggerUv (STAGE world XZ inches, then back to u/v).
  const k = familyK;
  const staggerStep = radialStagger;
  if (k === 0 || staggerStep === 0) {
    return [u, v];
  }
  const du = u - originU;
  const dv = v - originV;
  const x0 = stage.centerX + (originU - 0.5) * 2 * stage.halfWidthX;
  const z0 = stage.centerZ + (originV - 0.5) * 2 * stage.halfDepthZ;
  const x1 = stage.centerX + (u - 0.5) * 2 * stage.halfWidthX;
  const z1 = stage.centerZ + (v - 0.5) * 2 * stage.halfDepthZ;
  const dx = x1 - x0;
  const dz = z1 - z0;
  const worldDist = Math.sqrt(dx * dx + dz * dz);
  if (worldDist < 1e-6) {
    return [u, v];
  }
  const scale = (worldDist + Math.abs(k) * staggerStep) / worldDist;
  return [originU + du * scale, originV + dv * scale];
}

function generatePolarSnaps(cfg, stage) {
  const rings = cfg.snapGroups.length;
  const raw = [];
  for (let ringIndex = 1; ringIndex <= rings; ringIndex += 1) {
    const group = cfg.snapGroups[ringIndex - 1];
    const [kMin, kMax] = familyKBoundsForSnapCount(group.num);
    for (let rayIndex = 0; rayIndex < group.rays; rayIndex += 1) {
      const familyId = `${ringIndex}:${rayIndex}`;
      for (let k = kMin; k <= kMax; k += 1) {
        const [ringOriginU, ringOriginV] = ringOriginUvForIndex(cfg, ringIndex);
        const angleDeg = familyAngleDegForSnap(cfg, ringIndex, rayIndex, k, group.angleDelta, group.rays);
        let [u, v] = uvOnEllipse(ringOriginU, ringOriginV, angleDeg, group.maxU, group.maxV);
        if (group.radialStagger !== 0 && k !== 0) {
          [u, v] = applyRadialStaggerUv(ringOriginU, ringOriginV, k, group.radialStagger, u, v, stage);
        }
        if (!snapUvOnBoard(u, v)) {
          continue;
        }
        raw.push({
          snapKind: "polar",
          ringIndex,
          rayIndex,
          familyId,
          familyK: k,
          isAnchor: k === 0,
          u,
          v,
          defaultLightMode: group.defaultLightMode || "OFF",
        });
      }
    }
  }
  // Lua validSnaps is meant to drop unused rays on dense rings, not shrink a pack
  // whose anchor is in the box. Keep every on-board member of a family whose
  // k=0 snap passes the box (Center Left/Right stay at five in-game).
  const acceptedFamilies = new Set();
  for (const entry of raw) {
    const group = cfg.snapGroups[entry.ringIndex - 1];
    if (entry.isAnchor && snapUvPassesValidSnaps(group, entry.u, entry.v)) {
      acceptedFamilies.add(entry.familyId);
    }
  }
  const entries = [];
  for (const entry of raw) {
    const group = cfg.snapGroups[entry.ringIndex - 1];
    if (!acceptedFamilies.has(entry.familyId) && !snapUvPassesValidSnaps(group, entry.u, entry.v)) {
      continue;
    }
    entries.push({
      snapIndex: entries.length + 1,
      ...entry,
    });
  }
  return entries;
}

function generateSeatRowSnaps(seatRow) {
  const columns = seatRow.columns;
  const n = columns.length;
  return columns.map((col, i) => {
    const t = n === 1 ? 0.5 : i / (n - 1);
    const u = seatRow.uMin + t * (seatRow.uMax - seatRow.uMin);
    return {
      snapIndex: 0,
      snapKind: "seat",
      seatKey: col.seatKey,
      kind: col.kind,
      tableSlot: col.tableSlot,
      u,
      v: seatRow.v,
    };
  });
}

function generateScatterSlots(scatter) {
  const areas = {};
  for (const areaKey of scatter.areaOrder) {
    const area = scatter.areas[areaKey];
    if (!area) {
      throw new Error(`D.SCATTER_BOARD.areas is missing ${areaKey}.`);
    }
    const center = [];
    for (let slot = 1; slot <= scatter.centerSlotCount; slot += 1) {
      const deg = scatter.centerSlot1Deg + (slot - 1) * 72;
      const rad = (deg * Math.PI) / 180;
      center.push({
        slot,
        u: area.origin.u + Math.cos(rad) * area.centerRadius,
        v: area.origin.v + Math.sin(rad) * area.centerRadius,
      });
    }
    const orbit = [];
    for (let slot = 1; slot <= scatter.orbitSlotCount; slot += 1) {
      const deg = scatter.orbitSlot12Deg - slot * 30;
      const rad = (deg * Math.PI) / 180;
      orbit.push({
        slot,
        u: area.origin.u + Math.cos(rad) * area.orbitRadius,
        v: area.origin.v + Math.sin(rad) * area.orbitRadius,
      });
    }
    areas[areaKey] = { origin: area.origin, center, orbit };
  }
  return areas;
}

function parseControlBoardSnap(source) {
  const block = extractBlock(source, "D.CONTROL_BOARD_SNAP =");
  const origin = readUvOrigin(block);
  if (!origin) {
    throw new Error("D.CONTROL_BOARD_SNAP is missing origin u/v.");
  }
  const snapGroupsMatch = block.match(/snapGroups\s*=\s*\{/);
  if (!snapGroupsMatch || snapGroupsMatch.index === undefined) {
    throw new Error("D.CONTROL_BOARD_SNAP is missing snapGroups.");
  }
  const groupsStart = block.indexOf("{", block.indexOf("snapGroups"));
  let depth = 0;
  let groupsEnd = groupsStart;
  for (let i = groupsStart; i < block.length; i += 1) {
    if (block[i] === "{") {
      depth += 1;
    } else if (block[i] === "}") {
      depth -= 1;
      if (depth === 0) {
        groupsEnd = i;
        break;
      }
    }
  }
  const groupsBlock = block.slice(groupsStart, groupsEnd + 1);
  const snapGroups = parseAnonymousTableBodies(groupsBlock).map((body, index) => {
    const num = readNumberField(body, "num");
    const angleDelta = readNumberField(body, "angleDelta");
    const rays = readNumberField(body, "rays");
    const maxU = readNumberField(body, "maxU");
    const maxV = readNumberField(body, "maxV");
    if (num === null || angleDelta === null || rays === null || maxU === null || maxV === null) {
      throw new Error(`CONTROL_BOARD_SNAP snapGroups[${index + 1}] is missing num/angleDelta/rays/maxU/maxV.`);
    }
    return {
      num,
      angleDelta,
      rays,
      radialStagger: readNumberField(body, "radialStagger") ?? 0,
      maxU,
      maxV,
      origin: readUvOrigin(body),
      defaultLightMode: readStringField(body, "defaultLightMode") || "OFF",
      validSnaps: body.includes("validSnaps") ? readValidSnaps(body) : null,
    };
  });
  if (snapGroups.length === 0) {
    throw new Error("D.CONTROL_BOARD_SNAP.snapGroups is empty.");
  }
  return { origin, snapGroups };
}

function parseSeatRow(source) {
  const block = extractBlock(source, "D.CONTROL_BOARD_SEAT_ROW =");
  const v = readNumberField(block, "v");
  const uMin = readNumberField(block, "uMin");
  const uMax = readNumberField(block, "uMax");
  if (v === null || uMin === null || uMax === null) {
    throw new Error("D.CONTROL_BOARD_SEAT_ROW is missing v/uMin/uMax.");
  }
  const columnsBlockStart = block.indexOf("columns");
  if (columnsBlockStart < 0) {
    throw new Error("D.CONTROL_BOARD_SEAT_ROW is missing columns.");
  }
  const columnsBrace = block.indexOf("{", columnsBlockStart);
  let depth = 0;
  let end = columnsBrace;
  for (let i = columnsBrace; i < block.length; i += 1) {
    if (block[i] === "{") {
      depth += 1;
    } else if (block[i] === "}") {
      depth -= 1;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  const columns = parseAnonymousTableBodies(block.slice(columnsBrace, end + 1)).map((body, index) => {
    const seatKey = readStringField(body, "seatKey");
    const kind = readStringField(body, "kind");
    const tableSlot = readNumberField(body, "tableSlot");
    if (!seatKey || !kind || tableSlot === null) {
      throw new Error(`CONTROL_BOARD_SEAT_ROW.columns[${index + 1}] is missing seatKey/kind/tableSlot.`);
    }
    return { seatKey, kind, tableSlot };
  });
  if (columns.length === 0) {
    throw new Error("D.CONTROL_BOARD_SEAT_ROW.columns is empty.");
  }
  return { v, uMin, uMax, columns };
}

function parseScatterBoard(source) {
  const block = extractBlock(source, "D.SCATTER_BOARD =");
  const centerSlotCount = readNumberField(block, "centerSlotCount");
  const orbitSlotCount = readNumberField(block, "orbitSlotCount");
  const centerSlot1Deg = readNumberField(block, "centerSlot1Deg");
  const orbitSlot12Deg = readNumberField(block, "orbitSlot12Deg");
  if (centerSlotCount === null || orbitSlotCount === null || centerSlot1Deg === null || orbitSlot12Deg === null) {
    throw new Error("D.SCATTER_BOARD is missing slot counts or slot angles.");
  }
  const areaOrder = [];
  const orderMatch = block.match(/areaOrder\s*=\s*\{([^}]*)\}/);
  if (!orderMatch) {
    throw new Error("D.SCATTER_BOARD is missing areaOrder.");
  }
  for (const m of orderMatch[1].matchAll(/"([^"]+)"/g)) {
    areaOrder.push(m[1]);
  }
  const areasBlock = extractBlock(block, "areas =");
  const areas = {};
  for (const entry of parseTopLevelEntries(areasBlock)) {
    const origin = readUvOrigin(entry.body);
    const centerRadius = readNumberField(entry.body, "centerRadius");
    const orbitRadius = readNumberField(entry.body, "orbitRadius");
    if (!origin || centerRadius === null || orbitRadius === null) {
      throw new Error(`D.SCATTER_BOARD.areas.${entry.key} is missing origin/centerRadius/orbitRadius.`);
    }
    areas[entry.key] = { origin, centerRadius, orbitRadius };
  }
  return { areaOrder, centerSlotCount, orbitSlotCount, centerSlot1Deg, orbitSlot12Deg, areas };
}

function parsePlayerColors(source) {
  const block = extractBlock(source, "C.PlayerColors =");
  const colors = [...block.matchAll(/"([^"]+)"/g)].map((m) => m[1]);
  if (colors.length === 0) {
    throw new Error("C.PlayerColors is empty.");
  }
  return colors;
}

function parseNpcSeats(source) {
  const block = extractBlock(source, "C.NPCSeats =");
  const seats = [...block.matchAll(/"([^"]+)"/g)].map((m) => m[1]);
  if (seats.length === 0) {
    throw new Error("C.NPCSeats is empty.");
  }
  return seats;
}

function main() {
  const constants = fs.readFileSync(constantsPath, "utf8");
  const skyboxesSrc = fs.readFileSync(skyboxesPath, "utf8");
  const soundscapeSrc = fs.readFileSync(soundscapePath, "utf8");
  const conditionSrc = fs.readFileSync(conditionDefsPath, "utf8");
  const npcsSrc = fs.readFileSync(npcsDataPath, "utf8");
  const boardSrc = fs.readFileSync(gameboardDataPath, "utf8");

  const playerColors = parsePlayerColors(constants);
  const npcSeats = parseNpcSeats(constants);

  const districts = parseTopLevelEntries(extractBlock(constants, "C.Districts =")).map((entry) => ({
    key: entry.key,
    name: readStringField(entry.body, "name") || entry.key,
  }));
  districts.sort((a, b) => a.name.localeCompare(b.name));

  const sites = parseTopLevelEntries(extractBlock(constants, "C.Sites =")).map((entry) => {
    const districtMatch = entry.body.match(/district\s*=\s*C\.Districts\.([A-Za-z_][A-Za-z0-9_]*)/);
    const soundTrackMatch = entry.body.match(/track\s*=\s*"([^"]+)"/);
    const topFog = readBooleanField(entry.body, "topFog");
    const isTopFogActive = readBooleanField(entry.body, "isTopFogActive");
    return {
      key: entry.key,
      name: readStringField(entry.body, "name") || entry.key,
      districtKey: districtMatch ? districtMatch[1] : null,
      lightMode: readStringField(entry.body, "lightMode"),
      topFog: isTopFogActive !== null ? isTopFogActive : topFog,
      isIndoors: readBooleanField(entry.body, "isIndoors"),
      skybox: readStringField(entry.body, "skybox"),
      locationTrack: soundTrackMatch ? soundTrackMatch[1] : null,
    };
  });
  sites.sort((a, b) => a.name.localeCompare(b.name));

  const tables = parseTopLevelEntries(extractBlock(constants, "C.Tables =")).map((entry) => {
    const slotCapacity = readNumberField(entry.body, "slotCapacity");
    if (slotCapacity === null) {
      throw new Error(`C.Tables[${JSON.stringify(entry.key)}] is missing slotCapacity.`);
    }
    return { key: entry.key, slotCapacity };
  });

  const lightModes = parseTopLevelEntries(extractBlock(constants, "C.LightModes =")).map((entry) => entry.key);

  const skyboxes = parseTopLevelEntries(extractBlock(skyboxesSrc, "SkyboxesCatalog.Skyboxes ="))
    .filter((entry) => readBooleanField(entry.body, "isShown") !== false)
    .map((entry) => ({
      key: entry.key,
      display: readStringField(entry.body, "display") || entry.key,
    }));

  const locationTracks = parseTopLevelEntries(extractBlock(soundscapeSrc, "Catalog.TRACKS ="))
    .filter((entry) => readStringField(entry.body, "type") === "location")
    .map((entry) => ({
      key: readStringField(entry.body, "key") || entry.key,
      id: entry.key,
    }));

  const playlistsBlock = extractBlock(soundscapeSrc, "Catalog.PLAYLISTS =");
  const bgBlock = extractBlock(playlistsBlock, "backgroundMusic =");
  const backgroundMoods = parseTopLevelEntries(bgBlock).map((entry) => entry.key);

  const weatherConditions = parseTopLevelEntries(extractBlock(soundscapeSrc, "Catalog.WEATHER_CONDITIONS =")).map(
    (entry) => ({
      key: entry.key,
      label: readStringField(entry.body, "label") || entry.key,
      rain: readStringField(entry.body, "rain"),
      wind: readStringField(entry.body, "wind"),
      thunderEnabled: readBooleanField(entry.body, "thunderEnabled") === true,
    }),
  );

  const conditions = parseTopLevelEntries(extractBlock(conditionSrc, "CD.Defs ="))
    .filter((entry) => readBooleanField(entry.body, "canApplyManually") === true)
    .map((entry) => ({
      id: readStringField(entry.body, "id") || entry.key,
      displayName: readStringField(entry.body, "displayName") || entry.key,
    }));

  const characters = parseTopLevelEntries(extractBlock(npcsSrc, "D.characters =")).map((entry) => {
    const groupsBlockMatch = entry.body.match(/groups\s*=\s*\{([^}]*)\}/);
    const groups = [];
    const groupRanks = {};
    if (groupsBlockMatch) {
      for (const m of groupsBlockMatch[1].matchAll(/([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(-?\d+)/g)) {
        groups.push(m[1]);
        groupRanks[m[1]] = Number(m[2]);
      }
    }
    return {
      characterKey: entry.key,
      fullName: readStringField(entry.body, "fullName") || readStringField(entry.body, "name") || entry.key,
      isPC: readBooleanField(entry.body, "isPC") === true,
      groups,
      groupRanks,
      pickerGroups: groups.filter((g) => PALETTE_GROUP_BLACKLIST[g] !== true),
    };
  });

  const pcs = characters.filter((c) => c.isPC);
  const namedNpcs = characters.filter((c) => !c.isPC);

  const chronicleBlock = extractBlock(constants, "C.CHRONICLE_DATA =");
  const coterieEntries = parseTopLevelEntries(extractBlock(chronicleBlock, "coteries ="));
  if (coterieEntries.length === 0) {
    throw new Error("C.CHRONICLE_DATA.coteries extract is empty.");
  }
  const pickerGroupLabels = { ...EXTRA_PICKER_GROUP_LABELS };
  for (const entry of coterieEntries) {
    const name = readStringField(entry.body, "name");
    if (!name) {
      throw new Error(`C.CHRONICLE_DATA.coteries.${entry.key} is missing name.`);
    }
    pickerGroupLabels[entry.key] = name;
  }
  const missingGroupLabels = [];
  for (const npc of namedNpcs) {
    for (const group of npc.pickerGroups) {
      if (!pickerGroupLabels[group]) {
        missingGroupLabels.push(group);
      }
    }
  }
  const uniqueMissing = [...new Set(missingGroupLabels)].sort();
  if (uniqueMissing.length > 0) {
    throw new Error(
      `No display name for NPC picker group(s): ${uniqueMissing.join(", ")}. Add them to C.CHRONICLE_DATA.coteries or EXTRA_PICKER_GROUP_LABELS.`,
    );
  }

  const stage = loadDashboardStageWorld();
  const snapCfg = parseControlBoardSnap(boardSrc);
  const seatRow = parseSeatRow(boardSrc);
  const scatter = parseScatterBoard(boardSrc);
  const polarSnaps = generatePolarSnaps(snapCfg, stage);
  const seatSnaps = generateSeatRowSnaps({ ...seatRow, ...DASHBOARD_SEAT_ROW_UV });
  seatSnaps.forEach((snap, i) => {
    snap.snapIndex = polarSnaps.length + i + 1;
  });
  const scatterAreas = generateScatterSlots(scatter);

  const missingPcs = REQUIRED_PC_KEYS.filter((key) => !pcs.some((pc) => pc.characterKey === key));
  if (missingPcs.length > 0) {
    throw new Error(`D.characters is missing required PC key(s): ${missingPcs.join(", ")}`);
  }
  for (const color of REQUIRED_PLAYER_COLORS) {
    if (!playerColors.includes(color)) {
      throw new Error(`C.PlayerColors is missing ${color}.`);
    }
  }
  for (const seat of REQUIRED_NPC_SEATS) {
    if (!npcSeats.includes(seat)) {
      throw new Error(`C.NPCSeats is missing ${seat}.`);
    }
  }
  if (!tables.some((t) => t.key === "Table A")) {
    throw new Error('C.Tables is missing "Table A".');
  }
  if (districts.length === 0) {
    throw new Error("C.Districts extract is empty.");
  }
  if (sites.length === 0) {
    throw new Error("C.Sites extract is empty.");
  }
  if (lightModes.length === 0) {
    throw new Error("C.LightModes extract is empty.");
  }
  if (skyboxes.length === 0) {
    throw new Error("SkyboxesCatalog.Skyboxes extract is empty.");
  }
  if (locationTracks.length === 0) {
    throw new Error("Catalog.TRACKS location extract is empty.");
  }
  if (conditions.length === 0) {
    throw new Error("CD.Defs extract found no canApplyManually conditions.");
  }
  if (namedNpcs.length === 0) {
    throw new Error("D.characters extract found no named NPCs.");
  }
  if (polarSnaps.length === 0) {
    throw new Error("CONTROL_BOARD polar snap generation produced zero snaps.");
  }
  for (const areaKey of REQUIRED_SCATTER_AREAS) {
    const area = scatterAreas[areaKey];
    if (!area || area.center.length !== 5 || area.orbit.length !== 12) {
      throw new Error(`Scatter area ${areaKey} is missing generated center/orbit slots.`);
    }
  }

  const catalogs = {
    generatedBy: DO_NOT_EDIT,
    playerColors,
    npcSeats,
    pcs,
    namedNpcs,
    districts,
    sites,
    tables,
    lightModes,
    skyboxes,
    locationTracks,
    backgroundMoods,
    weatherConditions,
    conditions,
    pickerGroupLabels,
  };

  const snaps = {
    generatedBy: DO_NOT_EDIT,
    stageBoard: stage.stageBoard,
    polar: polarSnaps,
    seats: seatSnaps,
    scatter: {
      areaOrder: scatter.areaOrder,
      areas: scatterAreas,
    },
  };

  fs.mkdirSync(path.dirname(catalogsOutPath), { recursive: true });
  fs.writeFileSync(catalogsOutPath, `${JSON.stringify(catalogs, null, 2)}\n`);
  fs.writeFileSync(snapsOutPath, `${JSON.stringify(snaps, null, 2)}\n`);
  console.log(
    `Wrote ${path.relative(root, catalogsOutPath)} (${namedNpcs.length} named NPCs, ${pcs.length} PCs) and ${path.relative(root, snapsOutPath)} (${polarSnaps.length} polar + ${seatSnaps.length} seats; STAGE_BOARD ${stage.stageBoard.scaleX} × ${stage.stageBoard.scaleZ}).`,
  );
}

main();
