-- Auto-generated by .tools/custom-ui-assets/build-upload-manifest-from-sites-constants.js
-- Paste into your TTS Global script.
-- Supports both legacy imageList/imageNames and DEBUG manifest batch spawning.
imageList =
{
}

-- Optional console usage once pasted into Global:
-- lua DEBUG.spawnCustomUiUploadBatchFromManifest(customUiUploadManifest, {columns = 8, gap = 2, startY = 3})
-- lua DEBUG.clearCustomUiUploadTokens()
