-- Auto-generated by tools/custom-ui-assets/build-upload-manifest.js
-- Paste into your TTS Global script.
-- Supports both legacy imageList/imageNames and DEBUG manifest batch spawning.
imageList =
{
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Advantages_active.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Advantages_hover.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Advantages_inactive.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Experience_active.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Experience_hover.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Experience_inactive.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Memoriam_active.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Memoriam_hover.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Memoriam_inactive.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Projects_active.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Projects_hover.webp",
  "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Projects_inactive.webp",
}

imageNames =
{
  "toggle_Advantages_active",
  "toggle_Advantages_hover",
  "toggle_Advantages_inactive",
  "toggle_Experience_active",
  "toggle_Experience_hover",
  "toggle_Experience_inactive",
  "toggle_Memoriam_active",
  "toggle_Memoriam_hover",
  "toggle_Memoriam_inactive",
  "toggle_Projects_active",
  "toggle_Projects_hover",
  "toggle_Projects_inactive",
}

customUiUploadManifest = {
  assets = {
    { name = "toggle_Advantages_active", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Advantages_active.webp" },
    { name = "toggle_Advantages_hover", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Advantages_hover.webp" },
    { name = "toggle_Advantages_inactive", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Advantages_inactive.webp" },
    { name = "toggle_Experience_active", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Experience_active.webp" },
    { name = "toggle_Experience_hover", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Experience_hover.webp" },
    { name = "toggle_Experience_inactive", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Experience_inactive.webp" },
    { name = "toggle_Memoriam_active", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Memoriam_active.webp" },
    { name = "toggle_Memoriam_hover", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Memoriam_hover.webp" },
    { name = "toggle_Memoriam_inactive", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Memoriam_inactive.webp" },
    { name = "toggle_Projects_active", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Projects_active.webp" },
    { name = "toggle_Projects_hover", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Projects_hover.webp" },
    { name = "toggle_Projects_inactive", fileUrl = "file:///D:/Projects/.CODING/toronto-rising-tts/assets/images/Right Sidebar/New 4/toggle_Projects_inactive.webp" },
  }
}

-- Optional console usage once pasted into Global:
-- lua DEBUG.spawnCustomUiUploadBatchFromManifest(customUiUploadManifest, {columns = 8, gap = 2, startY = 3})
-- lua DEBUG.clearCustomUiUploadTokens()
