-- Camera capture snapshot (generated by HUD_debugCameraSnapshot)
-- Paste one of the entries below into C.UniversalCameraAngles or C.RedCameraAngles.
-- Suggested mode key: <replace_me>

local CAPTURED_CAMERA_ENTRY = {
  cameraMode = "FirstPerson",
  position = Vector({0.0000, 5.8436, -50.8718}),
  pitch = 70.5275,
  yaw = 0.0000,
  distance = 16.5598,
}

-- Example paste targets:
C.UniversalCameraAngles["<replace_me>"] = CAPTURED_CAMERA_ENTRY
C.RedCameraAngles["<replace_me>"] = CAPTURED_CAMERA_ENTRY
