-- Camera capture snapshot (generated by HUD_debugCameraSnapshot)
-- Paste one of the entries below into C.UniversalCameraAngles or C.RedCameraAngles.
-- Suggested mode key: <replace_me>

local CAPTURED_CAMERA_ENTRY = {
  cameraMode = "FirstPerson",
  position = Vector({0.0000, 79.4413, 66.9976}),
  pitch = 34.4825,
  yaw = 177.8662,
  distance = 27.3856,
}

-- Example paste targets:
C.UniversalCameraAngles["<replace_me>"] = CAPTURED_CAMERA_ENTRY
C.RedCameraAngles["<replace_me>"] = CAPTURED_CAMERA_ENTRY
